### PR TITLE
Add gbm learner

### LINKED ISSUE #18: Add gbm
https://github.com/mlr-org/mlr/blob/master/R/RLearner_surv_gbm.R

### PR DESCRIPTION
**Pull request by adibender**
Fixes #18

### CODE REVIEW

**Comment by adibender** [comment]
- gbm only returns `lp`. Setting `type = "response"` changes nothing for `distribution="coxph"`
- there is an internal method that returns the baseline hazard, so could in theory be used to construct `distr`
- gbm only accepts formula of type `Surv(time, status)`, not `Surv(time, status, type = ...)`, even if `type = "right"`

**Comment by RaphaelS1** [comment]
Thanks @adibender !

> there is an internal method that returns the baseline hazard, so could in theory be used to construct distr

Hm, to be honest I think we are already pushing it constructing a `distr` using `survfit` but we do it because it is very standard. In this case I think leave how it is and the user can always use the compositor. Could you then get rid of the `distr6` package, keep the commented code in case we change our minds.


Would you be able to change the "default" for the `distribution` parameter to `coxph`. I know the default in the documentation is `bernoulli` but then as you change it this is not the default the user will actually be using, similarly for `keep.data` - but let me know if you disagree!

**Comment by adibender** [comment]
> Could you then get rid of the `distr6` package, keep the commented code in case we change our minds.

Will do. 

> Would you be able to change the "default" for the `distribution` parameter to `coxph`. I know the default in the documentation is `bernoulli` but then as you change it this is not the default the user will actually be using, similarly for `keep.data` - but let me know if you disagree!

I wasn't sure about this. Reading [this](https://mlr3book.mlr-org.com/ext-learner.html#learner-meta-information) section in the mlr book, they put a lot of emphasis on the fact that the default is not changed when defining the param set. But then I wonder when and how the user sees that the default has changed :man_shrugging:

**Comment by RaphaelS1** [comment]
> I wasn't sure about this. Reading this section in the mlr book, they put a lot of emphasis on the fact that the default is not changed when defining the param set. But then I wonder when and how the user sees that the default has changed 🤷‍♂

Interesting, I had not read that before. In my opinion, if the package default is changed before construction, then this should be the default for the hyper-parameter, so this is what I've done in `mlr3proba`. However this should be consistent with the rest of mlr3 so I'll leave it to @mllg for final say

**Comment by mllg** [comment]
We had some discussions about this, and I hope I remember the outcome correctly:

The default specified via `ParamXXX$new(..., default = "")` just documents what value is used if it is not explicitly set by the user. If you want to change the default (for whatever reason), you should set it in `learner$param_set$values` during construction and additionally document this.

For example, here we change the verbosity for xgboost and set a default for `nrounds` for the xgboost learner: https://github.com/mlr-org/mlr3learners/blob/master/R/LearnerClassifXgboost.R#L96

**Comment by RaphaelS1** [comment]
Okay, so the hyper-parameter defaults should be interpreted as "these are the defaults from the implemented package" and not "these are the defaults used in construction".

In which case @adibender could you just add a line to description and I'll merge this?

**Pull request merged**
