### PR TITLE
perf: optimize Rcpp

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by bblodfon** [comment]
I see some `const` and `&`, that's I guess to avoid creating a copy right? Also dev-check fails, is it due to that?

**Comment by m-muecke** [comment]
> I see some `const` and `&`, that's I guess to avoid creating a copy right? Also dev-check fails, is it due to that?

Yeah thats for passing args by reference and hence saving the copy. I believe dev-check if failing due to mlr3 changes, but will check it out.

**Review by bblodfon — COMMENTED** [review]
Max, for the `c_weight_survival_score` I think you've just changed the "spacing" of the code, right (not the logic)? I can't check line-to-line here, so please verify! (I had checked that the C code worked even though it is very complicated as we use it in a paper)

**Comment by m-muecke** [comment]
> Max, for the `c_weight_survival_score` I think you've just changed the "spacing" of the code, right (not the logic)? I can't check line-to-line here, so please verify! (I had checked that the C code worked even though it is very complicated as we use it in a paper)

Not quite, the args also passed by reference instead of copy.

**Pull request merged**
