### PR TITLE
Kde

### PR DESCRIPTION
**Pull request by RaphaelS1**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Thanks, can I ask for a few minor small changes:

1. Delete the commented out code
2. Change Distribution name to `paste(self$param_set$values$kernel, "KDE")`
3. Change Distribution short_name to `paste0(self$param_set$values$kernel, "_KDE")`

And is there a particular reason why `1` is used as the default bandwidth? And does it make sense to have a default? We could force the user to choose, unless there are some rule-of-thumb methods that you can think of?

**Comment by aintoha** [comment]
I don't think I added the default bandwidth. I removed the default value

**Comment by aintoha** [comment]
Removing the default bandwidth let the auto test tp fail with this comment 
`test_mlr_learners_density_kde.R:8: failure: autotest
`result` isn't true.
[predict()] learner 'dens.kde:pdf' on task 'feat_single_logical' failed: predict log has errors: invalid subscript type 'list`

**Comment by aintoha** [comment]
There are rule-of-thumb methods, but it will vary depending on the kernel the user input.

**Comment by RaphaelS1** [comment]
Okay, in which case there are three choices:

1. Create a default for bandwidth, and add to the documentation description something like: "a default bandwidth of X is chosen to prevent errors, but this should be chosen or tuned by the user".
2. Set the bandwidth default to something like `Inf` and add an assertion like `assert(self$param_set$values$bandwidth != Inf)` with an error message along the lines of "bandwidth must be chosen or tuned by the user
3. No default for bandwidth, see below for fixing test.

Choose 2) or 3) if there is no sensible option for all bandwidths. Alternatively, you could implement a `switch` to call the rule-of-thumb for each kernel, this might be a good idea if we expect a lot of users won't know a sensible bandwidth to set.

For the test, change line 5 to `learner = lrn("dens.kde", bw = 1)`.

**Comment by aintoha** [comment]
There is function from package `KernSmooth` that can compute a plug-in bandwidth for each kernel. But the problem is the names of the kernels are different.

Another way is using 1) but using Silverman's rule of thumb for Gaussian (Normal) kernel. From that, users can tune the bandwidth

**Comment by RaphaelS1** [comment]
> Another way is using 1) but using Silverman's rule of thumb for Gaussian (Normal) kernel. From that, users can tune the bandwidth

I think mixing 1) and 3) is a bad idea

> There is function from package KernSmooth that can compute a plug-in bandwidth for each kernel. But the problem is the names of the kernels are different.

There are 11 kernels in total, how complicated are the plug-ins to recode yourself?

**Comment by aintoha** [comment]
Let me see if I can find the exact formula. I don't expect it to be hard when it's simplified

**Comment by RaphaelS1** [comment]
Actually, another suggestion would be to copy what `stats::density` does and use the `stats::bandwidth` function. The problem here is that this should only be used on Gaussian kernels, but `stats::density` uses it on any kernel type.

**Comment by aintoha** [comment]
I thought `stats:: density` uses a default function.

**Comment by RaphaelS1** [comment]
The default only applies to Gaussian though, so it's not a great implementation...
Can you have a look at [this paper](https://shodhganga.inflibnet.ac.in/bitstream/10603/76765/9/09_chapter%203.pdf), particular section 3.3 pgs. 67-69 and equation (3.14). If that seems sensible to you then we could plug that in, using the `CoreStatistics` decorator in `distr6` to estimate k4. I'd be happy to implement this in a look-up function myself if it makes sense to you

**Comment by aintoha** [comment]
It will be quite complicated to implement. In you distr6, you already for the L2norm of the kernels. I'm not sure if you have \int u^2K(u) du but you can get that from website. So, I think using Silverman's rule of thumb is easier, the equation can be found in the paper on page 66, equation 3.5. 

In this paper, [https://core.ac.uk/download/pdf/6591111.pdf](url), Table 1 on page 7 already provide some constant  for some kernel.

**Comment by RaphaelS1** [comment]
> It will be quite complicated to implement. 

What will be? Re-writing `KernSmooth` or the paper I sent?

> So, I think using Silverman's rule of thumb is easier, the equation can be found in the paper on page 66, equation 3.5.

But doesn't this assume Gaussian?

**Comment by aintoha** [comment]
> What will be? Re-writing `KernSmooth` or the paper I sent?
The paper I mean. Because I think we will need to implement equation 3.14 and we don't have the integration \int K(x)^4 dx. 

> But doesn't this assume Gaussian?
Silverman's method is using the AMISE (equation 3.5 in the paper you sent). In this method, f is unknown and Silverman and compute f" by assuming f is Gaussian. But the term K (the kernel) is going to the kernel method users want to implement.

**Comment by RaphaelS1** [comment]
Can you please have a look at the file ExROT that I have just uploaded to this branch and let me know if it makes sense to you. You're right that we don't have that integral but we can calculate the fourth cumulant by using the `kthmoment` function in the `CoreStatistics` decorator

**Comment by aintoha** [comment]
yes, this makes sense.

**Comment by RaphaelS1** [comment]
Okay in which case to the bandwidth value please add `special_val = "exrot"`, then in the description briefly say what this is doing, I'll add the reference myself. Then add a conditional in `train` which in pseudo-code will be like

1. If bandwidth is given then pass this to `pdf`
2. Else if bandwidth missing or equals "exrot" then pass to `pdf` `exrot(kernel, N)` where `N = nrow(truth)`

Does that make sense to you?

**Comment by aintoha** [comment]
But why is sd is equal to 1 for normal?

**Comment by RaphaelS1** [comment]
Because variance for Normal always = 1

**Comment by aintoha** [comment]
I think the sd should be sd for f(x) but f(x) is unknown in this case, But let me double-check. I might be wrong.

**Comment by aintoha** [comment]
I'm wrong. I got confused with another method. That's right

**Comment by RaphaelS1** [comment]
> I'm wrong. I got confused with another method. That's right

Great so can you make those changes and we'll merge this

**Comment by aintoha** [comment]
> Okay in which case to the bandwidth value please add `special_val = "exrot"`, then in the description briefly say what this is doing, I'll add the reference myself. Then add a conditional in `train` which in pseudo-code will be like
> 
> 1. If bandwidth is given then pass this to `pdf`
> 2. Else if bandwidth missing or equals "exrot" then pass to `pdf` `exrot(kernel, N)` where `N = nrow(truth)`
> 
> Does that make sense to you?

I'm not sure about the the usage of `exrot(kernel, N)`. where does `x1` goes in this?

Also, do you mean changing to ParamDb$new(id = "bandwidth", special_val = "exrot", tags = "train")`?

**Comment by RaphaelS1** [comment]
> Also, do you mean changing to ParamDb$new(id = "bandwidth", special_val = "exrot", tags = "train")`

Exactly

> I'm not sure about the the usage of exrot(kernel, N). where does x1 goes in this?

`exrot` selects the bandwidth so plugs straight into the `pdf` equation

**Comment by aintoha** [comment]
I did that, but I have errors. I pushed it to GitHub

**Comment by RaphaelS1** [comment]
no changes have been pushed, please try again

**Comment by aintoha** [comment]
there is, it's in the kde branch

**Comment by RaphaelS1** [comment]
Sorry not sure why it wasn't appearing before. Okay:

1. Please change special_vals name to all lower case
2. `missing` only works if it the argument should be in the function parameters, which it isn't in this case. Instead you want to move that conditional above `pdf` and set it to either exrot or the given parameter. 

I've also pushed a minor change

**Comment by aintoha** [comment]
> Sorry not sure why it wasn't appearing before. Okay:
> 
> 1. Please change special_vals name to all lower case

I did, but it came out as error `Error in .subset2(public_bind_env, "initialize")(...) : 
  unused argument (special_vals = "exrot")`. So I remove the `special_vals`

> 2. `missing` only works if it the argument should be in the function parameters, which it isn't in this case. Instead you want to move that conditional above `pdf` and set it to either exrot or the given parameter.
 
Ok, I fixed this

**Comment by RaphaelS1** [comment]
Okay I decided that using a plug-in from a random PhD without any peer-review may not be the best idea so have reverted to Silverman's and added to the documentation a note that tuning is the best idea. Can you please add a couple of manual tests for the `pdf` and then we can merge

**Comment by fkiraly** [comment]
Sorry to be late - in my opinion, vanilla KDE should have a settable density, perhaps with a default that is whatever the vanilla density estimator `stats::density` does. 

Different from that should be KDEs that auto-set the bandwith. I think this is a separate learner, with different ways to set the bandwidth either parameters, or different learnerse in that class.

**Comment by RaphaelS1** [comment]
Agreed, this is precisely what I've settled on in the end. We have LearnerDensKDE which is the most vanilla flavour and users can tune over kernel and bandwidth if they want. Otherwise any of the other learners that Ain has implemented can be used for other automated selection methods

**Comment by aintoha** [comment]
> Okay I decided that using a plug-in from a random PhD without any peer-review may not be the best idea so have reverted to Silverman's and added to the documentation a note that tuning is the best idea. Can you please add a couple of manual tests for the `pdf` and then we can merge

Alright, I already add one manual test, but because the numbers are in decimal, I added 1round1

**Pull request merged**
