### PR TITLE
remove distr prediction from rpart survival learner

### PR DESCRIPTION
**Pull request by bblodfon**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Thanks for this! I'll fix the underlying error then merge.

**Comment by bblodfon** [comment]
@RaphaelS1 I am trying to fix the errors! Some are ggplot updates + an old one with the distrcompositor => see this [line](https://github.com/mlr-org/mlr3proba/blob/main/R/pipelines.R#L242) that causes it. Every learner that has `lp` or `crank` prediction will fail at that point (when `graph_learner = TRUE`). I think we can do without that line? `gr` has all prediction types and the `GraphLearner` needs a `prediction_type` slot which I think it get assigned to the default/first from the learner used -does it make sense to put `distr` there?

**Comment by RaphaelS1** [comment]
@bblodfon you've contributed a lot to the package - do you want to add your name to the DESCRIPTION ?

**Review by RaphaelS1 — APPROVED** [review]

**Comment by bblodfon** [comment]
Thanks @RaphaelS1 , I've added my name!

**Pull request merged**
