### PR TITLE
RCLL bug (1 observation in test set)

### PR DESCRIPTION
**Pull request by bblodfon**
added one more test (very edge case) to show that the calculation of RCLL still fails

### CODE REVIEW

**Comment by bblodfon** [comment]
Hi @RaphaelS1 , #321 was still failing due to `prediction$distr[!event]$survival(cens_times)` being a single number and not a matrix (edge case here is one observation and one timepoint)

I added a simple fix on the RCLL measure + 1 more test. But maybe it's something that should be fixed on `distr6` you think?

**Comment by RaphaelS1** [comment]
Sorry not entirely sure I understand, can you send a reprex of the error?

**Comment by bblodfon** [comment]
Yes, here it is:
``` r
# https://github.com/mlr-org/mlr3proba/issues/321
library(mlr3verse)
#> Loading required package: mlr3
library(mlr3proba)

# veteran task
taskv = as_task_surv(x = survival::veteran, id = 'veteran',
  time = 'time', event = 'status')
poe = po('encode')
taskv = poe$train(list(taskv))[[1L]]

set.seed(42)
rr = resample(task = taskv, learner = lrn('surv.coxph'),
  resampling = rsmp('cv', folds = 8))

rcll = msr('surv.rcll')
rr$score(rcll) # error
#> Error in out[!event] <- diag(prediction$distr[!event]$survival(cens_times)): replacement has length zero

# RCLL code check
dt = as.data.table(rr)
prediction = dt$prediction[[3]]
prediction$score(rcll) # error
#> Error in out[!event] <- diag(prediction$distr[!event]$survival(cens_times)): replacement has length zero

out = rep(-99L, length(prediction$row_ids))
truth = prediction$truth
event = truth[, 2] == 1
event_times = truth[event, 1]
cens_times = truth[!event, 1]

# HERE!!!!!
!event # one TRUE only
#>  [1] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#> [13] FALSE FALSE FALSE FALSE FALSE
prediction$distr[!event]$survival(cens_times) # single number, maybe it should be matrix from distr6?
#> [1] 0.07378455
diag(prediction$distr[!event]$survival(cens_times)) # diag returns empty matrix
#> <0 x 0 matrix>
diag(as.matrix(prediction$distr[!event]$survival(cens_times))) # so I did this to make it work
#> [1] 0.07378455
```

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RaphaelS1** [comment]
Got it. Yeah this is a proba fix not distr6

**Review by RaphaelS1 — APPROVED** [review]

**Pull request merged**
