### PR TITLE
Adds obliqueRSF learner

### LINKED ISSUE #55: Add oblique random survival forests
https://cran.r-project.org/web/packages/obliqueRSF/

### PR DESCRIPTION
**Pull request by adibender**
Fixes #55

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Thanks @adibender, when you get a chance can you figure out what's causing the build to fail?

**Comment by adibender** [comment]
I'll try.

**Comment by RaphaelS1** [comment]
I did some digging in the code of `ORSF`.
Line 34: `model.matrix(~., data = data[, features])[, -1L]`
The problem is the default option for `data.frame` is `drop = FALSE` and they don't specify `drop = TRUE`, so on selecting one feature it reduces to a numeric.

I believe this is a bug upstream (assuming they want to include the single variable case). Even on adding `drop = T` there are still problems resulting from their internal `ORSFcpp` function. My suggestion for now is to exclude  'single' tests and open an issue upstream. Thoughts/opinions appreciated

**Comment by adibender** [comment]
nice, thanks for investigating. I wouldn't sweat it, we can just leave the PR open for now and see if upstream is going to be fixed soon (https://github.com/bcjaeger/obliqueRSF/issues/1)

**Comment by RaphaelS1** [comment]
Cool, but if not I wouldn't worry too much about the single feature case. `surv.svm` has the same problem, I think most developers just assume it's a rare use-case that can be ignored.

**Comment by adibender** [comment]
yeah, fitting ML methods to one feature data sets probably not very useful, especially for obliqueRSF which fits a elastic net Cox PH model in each node...

**Comment by RaphaelS1** [comment]
Ok, let's just exclude single tests for now and if they fix your issue we can include these tests.

**Pull request merged**
