### PR TITLE
Add citation information

### PR DESCRIPTION
**Pull request by adibender**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
I'm happy to add this but we last agreed we wouldn't add the arxiv citation but wait until we hear back from Bio. I guess there's no harm in having this in the interim though...

**Comment by RaphaelS1** [comment]
Can you please also add bibtex to readme.rmd ?

**Comment by adibender** [comment]
> I'm happy to add this but we last agreed we wouldn't add the arxiv citation but wait until we hear back from Bio. I guess there's no harm in having this in the interim though...

Let's keep this open then and I'll replace the info once published

**Comment by RaphaelS1** [comment]
thanks both

**Pull request merged**
