### PR TITLE
measure optimizations and documentation updates

### PR DESCRIPTION
**Pull request by RaphaelS1**
Added methods so calib alpha and beta can be minimised

### CODE REVIEW

**Comment by jemus42** [comment]
What's the status here? I'd like to try the difference method soonish -- should I rather test-drive the PR first?

**Comment by jemus42** [comment]
Just notice that our issue of getting `Inf` here doesn't go away because the issue appears to be in 

```r
out = deaths / sum(haz)
```

where for some reason `sum(haz)` appears to be 0, so

```r 
out = abs(1 - out)
```

will still give us an `Inf`.
I may also have forgotten what we get by using the difference method but I had just been staring at the `Inf`s in my `bma` and noticed this 😅

**Comment by bblodfon** [comment]
- Update/refine all measure docs
- `logloss` optimized to use survival matrices
- `beta_calib` diff version tested

**Comment by bblodfon** [comment]
addresses #350

**Review by bblodfon — APPROVED** [review]
Approved

**Pull request merged**
