### PR TITLE
Pengss -> spline

### PR DESCRIPTION
**Pull request by RaphaelS1**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Thanks.

1. Please move all code in `DensGss` into the main file
2. Please rename to something like `LearnerDensSpline`/`dens.spline` and update `zzz.R`, documentation, and distribution name/short_name accordingly
3. Please add `cdf`, and `quantile` by using `gss:pssden` and `gss:qssden`
4. Add `cdf` predict type
5. Please delete param `subset`
6. Please check the param types, a few of these should be `ParamDbl` not `ParamUty`, where this is true please add `lower` and `upper`
7. Where `default = NULL` please just remove `default`

**Comment by aintoha** [comment]
> 3. Please add `cdf`, and `quantile` by using `gss:pssden` and `gss:qssden`

where to put the 'quantile`?

**Comment by RaphaelS1** [comment]
Its identical to pdf and cdf. Just another argument to Distribution

**Comment by aintoha** [comment]
> Its identical to pdf and cdf. Just another argument to Distribution

I did that but for `quantile` it will have error

**Pull request merged**
