### PR TITLE
fix pipeline dependency

### PR DESCRIPTION
**Pull request by sebffischer**
mlr3pipelines was in Suggests but due to the inheritance structure it was actually a dependency. 
This is fixed in this PR by using `delayedAssign`

### CODE REVIEW

**Review by RaphaelS1 — APPROVED** [review]
Thanks. Will merge after #262

**Comment by sebffischer** [comment]
ups sorry i didnt read the comment and merged, is this a problem?

**Comment by RaphaelS1** [comment]
No but in the future please don't merge a PR without me knowing, just ping me repeatedly if it's urgent

**Comment by sebffischer** [comment]
I just saw that you approved it but didn’t read the comment

**Pull request merged**
