### PR TITLE
Loglocfit

### PR DESCRIPTION
**Pull request by RaphaelS1**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
Thanks.

1. Should param `cut` be `ParamDbl`? Unsure
2. I think params `family` and `link` should be `ParamFct`, again unsure
3. Can you explain where the "log" in the name comes from? I can't see any reference to this. If not needed please change name to `LearnerDensLocfit`/`dens.locfit` and update `zzz.R`, documentation and distr6 distribution accordingly
4. Be careful in distribution name, if default kernel is used this wille error, use if/else to fix

**Comment by aintoha** [comment]
what does codecov report mean?

**Comment by RaphaelS1** [comment]
Ignore it

**Comment by fkiraly** [comment]
@aintoha , have a read here
https://en.wikipedia.org/wiki/Code_coverage
In a high quality software project like this you want a high *code coverage* by *sensible tests*. Sensible means typical usage, corner cases, etc. It´s easy to "cheat" here and get a high coverage that is not sensible. 
Nothing you need to take care of for this module though.

**Comment by RaphaelS1** [comment]
Where did you find the levels of the `window/kern` param?

**Comment by aintoha** [comment]
> Where did you find the levels of the `window/kern` param?

i might be misunderstood when it mentions `density`.  But I think it uses window

**Comment by RaphaelS1** [comment]
but where did you find the values it can take?

**Comment by aintoha** [comment]
> but where did you find the values it can take?

it takes the same kernel as the `stats::density` from I what I understand.

**Comment by aintoha** [comment]
> > but where did you find the values it can take?
> 
> it takes the same kernel as the `stats::density` from I what I understand.

"This function provides an interface to Locfit, in the syntax of (a now old version of) the S-Plus
density function."

**Comment by RaphaelS1** [comment]
> "This function provides an interface to Locfit, in the syntax of (a now old version of) the S-Plus
density function."

Hm I don't think this is correct. Here is how I read it (and I think their documentation is a mess, hence the confusion):

* From documentation of `density.lf`: "Window type to use for estimation. Equivalent to the locfit.raw kernargument. This includes all the density windows except cosine."
* Then looking at `locfit.raw` kern documentation: "Weight function, default = "tcub". Other choices are "rect", "trwt", "tria", "epan", "bisq" and "gauss". Choices may be restricted when derivatives are required; e.g. for confidence bands and some bandwidth selectors."

But these choices are not consistent with the default for `density.lf`, which is "gaussian"

**Comment by aintoha** [comment]
Yes, when I made this function,  I used all the `kernel` from `stats::density`. When I use the `kern`, it comes out as error. 

I know what you mean, I had to read it many times. So, I tried using the different parameters

**Pull request merged**
